import keyMirror from 'keymirror';

export default keyMirror({

    //EMPLOYEES
    LIST_EMPLOYEES: null,
    LIST_EMPLOYEES_SUCCESS: null,
    LIST_EMPLOYEES_ERROR: null,

    DISINCORPORATE_EMPLOYEE: null,
    DISINCORPORATE_EMPLOYEE_SUCCESS: null,
    DISINCORPORATE_EMPLOYEE_ERROR: null,

    NEW_EMPLOYEE: null,
    NEW_EMPLOYEE_SUCCESS: null,
    NEW_EMPLOYEE_ERROR: null,

    SELECT_EMPLOYEE_TO_EDIT:null,

    EDIT_EMPLOYEE: null,
    EDIT_EMPLOYEE_SUCCESS: null,
    EDIT_EMPLOYEE_ERROR: null,

    SEARCH: null,
    SEARCH_SUCCESS: null,
    SEARCH_ERROR: null,

    LIST_PM: null,
    LIST_PM_SUCCESS: null,
    LIST_PM_ERROR: null,

    FROM: null,

    //DISINCORPORATED
    LIST_DISINCORPORATED: null,
    LIST_DISINCORPORATED_SUCCESS: null,
    LIST_DISINCORPORATED_ERROR: null,

    INCORPORATE_EMPLOYEE: null,
    INCORPORATE_EMPLOYEE_SUCCESS: null,
    INCORPORATE_EMPLOYEE_ERROR: null,

    INCORPORATE_PROSPECT: null,
    INCORPORATE_PROSPECT_SUCCESS: null,
    INCORPORATE_PROSPECT_ERROR: null,

    //PROSPECTS
    LIST_PROSPECTS: null,
    LIST_PROSPECTS_SUCCESS: null,
    LIST_PROSPECTS_ERROR: null,  

    DISINCORPORATE_PROSPECT: null,
    DISINCORPORATE_PROSPECT_SUCCESS: null,
    DISINCORPORATE_PROSPECT_ERROR: null,

    DELETE_PROSPECT: null,
    DELETE_PROSPECT_SUCCESS: null,
    DELETE_PROSPECT_ERROR: null,

    NEW_PROSPECT: null,
    NEW_PROSPECT_SUCCESS: null,
    NEW_PROSPECT_ERROR: null,

    SELECT_PROSPECT_TO_EDIT:null,

    EDIT_PROSPECT: null,
    EDIT_PROSPECT_SUCCESS: null,
    EDIT_PROSPECT_ERROR: null,

    SELECT_PROSPECT_TO_HIRE:null,

    HIRE_PROSPECT: null,
    HIRE_PROSPECT_SUCCESS: null,
    HIRE_PROSPECT_ERROR: null,   

    FROM_PROSPECT: null,

    //CARGO
    LIST_CARGO: null,
    LIST_CARGO_SUCCESS: null,
    LIST_CARGO_ERROR: null,

    //DEPARTAMENTOS
    LIST_DTOS: null,
    LIST_DTOS_SUCCESS: null,
    LIST_DTOS_ERROR: null, 
    
    //PAGINACION
    LAST_PAGE_SUCCESS_EMPLOYEES: null,
    LAST_PAGE_ERROR_EMPLOYEES: null,

    LAST_PAGE_SUCCESS_PROSPECT: null,
    LAST_PAGE_ERROR_PROSPECT: null,

    LAST_PAGE_SUCCESS_DIS: null,
    LAST_PAGE_ERROR_DIS: null,

    LAST_PAGE_SUCCESS_ACTIVES: null,
    LAST_PAGE_ERROR_ACTIVES: null,

    LAST_PAGE_SUCCESS_PAUSED: null,
    LAST_PAGE_ERROR_PAUSED: null,

    LAST_PAGE_SUCCESS_CANCELED: null,
    LAST_PAGE_ERROR_CANCELED: null,

    PAGINACION_EMPLOYEES: null,
    PAGINACION_SUCCESS_EMPLOYEES: null,
    PAGINACION_ERROR_EMPLOYEES: null,

    PAGINACION_PROSPECT: null,
    PAGINACION_SUCCESS_PROSPECT: null,
    PAGINACION_ERROR_PROSPECT: null,

    PAGINACION_DIS: null,
    PAGINACION_SUCCESS_DIS: null,
    PAGINACION_ERROR_DIS: null,

    PAGINACION_ACTIVES: null,
    PAGINACION_SUCCESS_ACTIVES: null,
    PAGINACION_ERROR_ACTIVES: null,

    PAGINACION_PAUSED: null,
    PAGINACION_SUCCESS_PAUSED: null,
    PAGINACION_ERROR_PAUSED: null,

    PAGINACION_CANCELED: null,
    PAGINACION_SUCCESS_CANCELED: null,
    PAGINACION_ERROR_CANCELED: null,


    //ACTIVES
    NEW_PROJECT: null,
    NEW_PROJECT_SUCCESS: null,
    NEW_PROJECT_ERROR: null,

    PAUSAR_CANCELAR_ACTIVE: null,
    PAUSAR_CANCELAR_ACTIVE_SUCCESS: null,
    PAUSAR_CANCELAR_ACTIVE_ERROR: null,

    SEARCH_ACTIVES: null,
    SEARCH_ACTIVES_SUCCESS: null,
    SEARCH_ACTIVES_ERROR: null,

    OBTENER_PROYECTO_SUCCESS: null,
    OBTENER_PROYECTO_ERROR: null,

    SELECT_PROJECT_TO_EDIT: null,
    FROM_PROJECT:null,

    EDIT_PROJECT: null,
    EDIT_PROJECT_SUCCESS: null,
    EDIT_PROJECT_ERROR: null,

    LAST_PAGE_ACTIVES_SUCCESS: null,
    LAST_PAGE_ACTIVES_ERROR: null,


    //PAUSED
    SEARCH_PAUSED: null,
    SEARCH_PAUSED_SUCCESS: null,
    SEARCH_PAUSED_ERROR: null,

    ACTIVAR_CANCELAR_PAUSED: null,
    ACTIVAR_CANCELAR_PAUSED_SUCCESS: null,
    ACTIVAR_CANCELAR_PAUSED_ERROR: null,

    EDIT_PAUSED: null,
    EDIT_PAUSED_SUCCESS: null,
    EDIT_PAUSED_ERROR: null,

    LAST_PAGE_PAUSED_SUCCESS: null,
    LAST_PAGE_PAUSED_ERROR: null,

    //CANCELED
    SEARCH_CANCELED: null,
    SEARCH_CANCELED_SUCCESS: null,
    SEARCH_CANCELED_ERROR: null,

    ACTIVAR_PAUSAR_CANCELED: null,
    ACTIVAR_PAUSAR_CANCELED_SUCCESS: null,
    ACTIVAR_PAUSAR_CANCELED_ERROR: null,

    EDIT_CANCELED: null,
    EDIT_CANCELED_SUCCESS: null,
    EDIT_CANCELED_ERROR: null,

    LAST_PAGE_CANCELED_SUCCESS: null,
    LAST_PAGE_CANCELED_ERROR: null,

    //EXTRA
    TO_RELOAD: null,
    RELOAD_EMPLOYEES: null,
    RELOAD_PROSPECTS: null,
});